- name: remove mecab
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/mecab
    - /usr/bin/mecab-config
    - /usr/lib64/libmecab.so.2.0.0
    - /usr/lib64/libmecab.a
    - /usr/lib64/libmecab.la
    - /usr/lib64/libmecab.so.2
    - /usr/lib64/libmecab.so
    - /usr/lib64/libMeCab.so
    - /usr/libexec/mecab      # mecab-cost-train
    - /usr/share/man/man1/mecab.1
    - /etc/mecab              # mecabrc
    - /usr/lib64/mecab        # dic
