select
    ID,
    modelno,
    pl_no,
    modelno_group,
    DECODE(NVL(MODELNO_GROUP,0),0,0,1) AS MODELNO_GROUP_FLAG,
    UDF_CATEGORY_ALL(CATEGORY) AS category,
    CASE WHEN SERVICE_GUBUN = 1 THEN UDF_CATEGORY_SUB(CATEGORY,4) ELSE UDF_CATEGORY_SUB(CATEGORY,2) END AS CG,
    UDF_CATEGORY_SUB(CATEGORY,2) AS CAT1,
    UDF_CATEGORY_SUB(CATEGORY,4) AS CAT2,
    UDF_CATEGORY_SUB(CATEGORY,2) AS CAT3,
    UDF_CATEGORY_SUB(CATEGORY,2) AS CAT4,
    ca_code,
    ca_dept_mcode,
    ca_dept_code,
    ca_dept_dcode,
    ca_lcode_ran,
    ca_mcode_ran,
    ca_scode_ran,
    ca_dcode_ran,
    shop_code,
    shop_name,
    shop_name_code,
    modelnm,
    modelnm2,
    factory,
    brand,
    popular,
    popular2,
    sale_cnt,
    CASE WHEN SERVICE_GUBUN = 1 THEN REPLACE(MODELNM || ' ' || FACTORY, '-', '') ELSE '' END AS model_factory,
    minprice,
    maxprice,
    minprices,
    C_DATE,
    mallcnt,
    DECODE(NVL(MALLCNT,0),0,0,1) AS MALLCNT_FLAG,
    spec,
    openexpectflag,
    condiname,
    KEYWORD,
    keyword2,
    BRANDCODE1,
    BRANDCODE2,
    SPECOPT,
    bookflag,
    useflag,
    weight,
    minprice3,
    minprice2,
    maxprice3,
    mobile_flag,
    minprice4,
    store_flag,
    bbs_num,
    zum_check,
    service_gubun,
    minprice5,
    ext_condi_flag,
    MODELNM || ' ' || FACTORY || ' ' || SPEC || ' ' || KEYWORD || ' ' || KEYWORD2 || ' ' || CONDINAME AS to_all
from (

select    /*+ PARALLEL(3) */
    ID,
    modelno,
    pl_no,
    modelno_group,
    CASE WHEN service_gubun='2' AND store_flag='1' AND ca_dept_code IS NOT NULL THEN RTRIM(category || ' '  || ca_dept_code) ELSE category END AS category,
    ca_code,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),3,8)='000000' OR SUBSTR(RTRIM(ca_dept_code),3,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,4) END AS ca_dept_mcode,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),5,8)='0000' OR SUBSTR(RTRIM(ca_dept_code),5,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,6) END AS ca_dept_code,
    CASE WHEN SUBSTR(RTRIM(ca_dept_code),7,8)='00' OR SUBSTR(RTRIM(ca_dept_code),7,8) IS NULL THEN '' ELSE SUBSTR(RTRIM(ca_dept_code),0,8) END AS ca_dept_dcode,
    ca_lcode_ran,
    ca_mcode_ran,
    ca_scode_ran,
    ca_dcode_ran,
    shop_code,    
    shop_name,    
    shop_name_code,
    modelnm,
    modelnm2,
    factory,
    brand,
    popular,
    popular2,
    sale_cnt,
    model_factory,
    minprice,
    maxprice,
    replace(minprices, ' ', '    ') as minprices,
    C_DATE,
    mallcnt,
    replace(replace(spec,',',' '),'/',' ') spec,
    openexpectflag,
    replace(condiname, ' ', '    ') as condiname,    
    CASE WHEN socialprice=0 THEN keyword ELSE keyword || ' ' || UDF_SOCIAL_GOODSNM(modelno_group,modelno) END AS KEYWORD,    
    keyword2,
    BRANDCODE1,
    BRANDCODE2,
    SPECOPT,
    bookflag,
    useflag,
    weight,
    minprice3,
    minprice2,
    maxprice3,
    mobile_flag,
    minprice4,
    store_flag,
    bbs_num,
    zum_check,
    service_gubun,
    minprice5,
    ext_condi_flag
FROM (    
    SELECT
    'P' || P.pl_no ID,    
    P.pl_no MODELNO, 
    P.PL_NO pl_no,
    '0' modelno_group,
    CASE WHEN P.CA_CODE IS NULL THEN '000000' WHEN LENGTH(RTRIM(P.CA_CODE))=2 THEN RTRIM( P.CA_CODE) || '0000' WHEN LENGTH(RTRIM(P.CA_CODE))=4 THEN RTRIM(P.CA_CODE) || '00' ELSE P.CA_CODE END AS CATEGORY,
    CASE WHEN P.CA_CODE IS NULL THEN '000000' WHEN LENGTH(RTRIM(P.CA_CODE))=2 THEN RTRIM( P.CA_CODE) || '0000' WHEN LENGTH(RTRIM(P.CA_CODE))=4 THEN RTRIM(P.CA_CODE) || '00' ELSE P.CA_CODE END AS CA_CODE,
    CASE WHEN store_flag='1' THEN ca_code_dept ELSE '' END AS ca_dept_code, 
    '' AS ca_lcode_ran,
    '' AS ca_mcode_ran,
    '' AS ca_scode_ran,
    '' AS ca_dcode_ran,
    CASE WHEN SUBSTR(P.CA_CODE,0,4) = '9501' then UDF_GOODSNM_REMOVE(P.goodsnm) || ' 음반 앨범' else UDF_GOODSNM_REMOVE(P.goodsnm) end as modelnm ,
    CASE WHEN SUBSTR(P.CA_CODE,0,4) = '1219' THEN UDF_GOODSNM_REMOVE(P.goodsnm) ELSE '' END AS modelnm2,
    P.shop_code,    
    S.shop_name,    
    '' as shop_name_code,
    '[추가]' factory,   
    '기타' brand,
    NVL(P.POPULAR,0) AS POPULAR,
    NVL(P.POPULAR,0) AS POPULAR2,
        sale_cnt,
    '' model_factory,
    P.price minprice,    
    P.price maxprice,
    P.price || ' ' minprices,    
    TO_CHAR(P.U_DATE,'YYYYMMDDHH24MISS') AS C_DATE,    
    1 mallcnt,    
    ' ' spec,
    '0' openexpectflag,
    ' ' condiname,
    ' ' keyword,
    ' ' keyword2,
    ' ' brandcode1,
    ' ' brandcode2,
    ' ' specopt,
    CASE WHEN SUBSTR(P.CA_CODE,0,2) = '93' then '1' else '0' end as bookflag ,
    CASE WHEN SUBSTR(P.CA_CODE,0,2) = '93' then '0' else '1' end as useflag,
    0 weight,
    0 socialprice,
    (case when NVL(instance_price,0) = 0 then price else case when instance_price < price then instance_price else price end end) minprice3,
    CASE WHEN deliverytype2=0 THEN (price + 2500) ELSE (price + DECODE(deliveryinfo, '무료배송', 0, NVL(deliveryinfo2, 2500))) END minprice2,
    NVL(instance_price,0) maxprice3,
    CASE WHEN NVL(instance_price,0) = 0 then '0' else '1' end as mobile_flag,    
    CASE WHEN NVL(store_flag,'0')='1' THEN price ELSE 0 END AS minprice4,
    NVL(store_flag,'0') store_flag,
    0 bbs_num,
    UDF_ZUM_CHECK(P.shop_code) zum_check,
    '2' service_gubun,
    P.price minprice5,
    '0' as ext_condi_flag
    FROM   TBL_PRICELIST P    
      INNER JOIN TBL_SHOPLIST S    
      ON P.SHOP_CODE = S.SHOP_CODE    
      LEFT OUTER JOIN TBL_GOODS G    
      ON P.MODELNO = G.MODELNO AND G.CATEFLAG='0'    
    WHERE  P.SRVFLAG in ('0','L','R','Z','2','3','6','7','9','O','D','S','P')  
--    AND SUBSTR(P.CA_CODE,0,2) in ('86', '02', '14') 
    AND (
      P.modelno<=0        
      OR ( G.CONSTRAIN='1' AND G.JOBCODE = '0' )        
      OR ( G.CONSTRAIN IS NULL AND G.JOBCODE IS NULL )        
      OR G.CONSTRAIN IN ('2','3')
      OR (P.option_flag2='1' AND G.minprice < P.price)
      OR P.SRVFLAG IN ('Z','2','3','6','7','9','O','D','P')
    )        
    AND mod(P.pl_no, 8) = {{ pl_part }}
 )

)
