---

- hosts: elasticsearch
  remote_user: root
  vars:

  roles:
    - stops_installer

#- hosts: prod_data
#  remote_user: root
#  vars:
#    - es_state: restarted

#  roles:
#    - es_service_manager

