
- name: make mecab dictionary folder
  file:
    path: "{{ dic_dir }}"
    state: directory

- name: install mecab dictionary
  copy:
    src: "{{ item }}"
    dest: "{{ dic_dir }}/{{ item }}"
    mode: 0644
  with_items:
    - model.bin
    - matrix.bin
    - char.bin
    - sys.dic
    - unk.dic
    - left-id.def
    - right-id.def
    - rewrite.def
    - pos-id.def
    - dicrc
